[workspace]
members = [
    "kyute",    # user interface library - widgets and application architecture
    "kyute-shell",    # user interface library - windowing and system integration
    "kyute/macros"
]

[profile.release]
debug = true
