[workspace]
members = [
    "artifice",    # sample application
    "kyute",    # user interface library - widgets and application architecture
    "kyute-shell",    # user interface library - windowing and system integration
]

[profile.release]
debug = true
