[package]
name = "artifice"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = { version = "0.2.17", features = ["fmt"] }
kyute = { path="../kyute" }
tracing = "0.1.25"