[package]
name = "kyute"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = "2018"


[dependencies]
kyute-shell = { path="../kyute-shell" }
tracing = "0.1.25"
slotmap = "1.0.3"
euclid = "0.22.3"